[{
  "url": "https://api.github.com/repos/explosion/spaCy/issues/429",
  "repository_url": "https://api.github.com/repos/explosion/spaCy",
  "labels_url": "https://api.github.com/repos/explosion/spaCy/issues/429/labels{/name}",
  "comments_url": "https://api.github.com/repos/explosion/spaCy/issues/429/comments",
  "events_url": "https://api.github.com/repos/explosion/spaCy/issues/429/events",
  "html_url": "https://github.com/explosion/spaCy/issues/429",
  "id": 161079771,
  "node_id": "MDU6SXNzdWUxNjEwNzk3NzE=",
  "number": 429,
  "title": "pipe(): ValueError Error parsing doc",
  "user": {
    "login": "blang",
    "id": 803897,
    "node_id": "MDQ6VXNlcjgwMzg5Nw==",
    "avatar_url": "https://avatars3.githubusercontent.com/u/803897?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/blang",
    "html_url": "https://github.com/blang",
    "followers_url": "https://api.github.com/users/blang/followers",
    "following_url": "https://api.github.com/users/blang/following{/other_user}",
    "gists_url": "https://api.github.com/users/blang/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/blang/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/blang/subscriptions",
    "organizations_url": "https://api.github.com/users/blang/orgs",
    "repos_url": "https://api.github.com/users/blang/repos",
    "events_url": "https://api.github.com/users/blang/events{/privacy}",
    "received_events_url": "https://api.github.com/users/blang/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 111380485,
      "node_id": "MDU6TGFiZWwxMTEzODA0ODU=",
      "url": "https://api.github.com/repos/explosion/spaCy/labels/bug",
      "name": "bug",
      "color": "DD2A27",
      "default": true
    }
  ],
  "state": "closed",
  "locked": true,
  "assignee": null,
  "assignees": [

  ],
  "milestone": {
    "url": "https://api.github.com/repos/explosion/spaCy/milestones/1",
    "html_url": "https://github.com/explosion/spaCy/milestone/1",
    "labels_url": "https://api.github.com/repos/explosion/spaCy/milestones/1/labels",
    "id": 2018336,
    "node_id": "MDk6TWlsZXN0b25lMjAxODMzNg==",
    "number": 1,
    "title": "Version 1.0 Release",
    "description": "Bug fixes, enhancements, documentation for spaCy 1.0.",
    "creator": {
      "login": "ines",
      "id": 13643239,
      "node_id": "MDQ6VXNlcjEzNjQzMjM5",
      "avatar_url": "https://avatars0.githubusercontent.com/u/13643239?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ines",
      "html_url": "https://github.com/ines",
      "followers_url": "https://api.github.com/users/ines/followers",
      "following_url": "https://api.github.com/users/ines/following{/other_user}",
      "gists_url": "https://api.github.com/users/ines/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ines/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ines/subscriptions",
      "organizations_url": "https://api.github.com/users/ines/orgs",
      "repos_url": "https://api.github.com/users/ines/repos",
      "events_url": "https://api.github.com/users/ines/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ines/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 0,
    "closed_issues": 28,
    "state": "closed",
    "created_at": "2016-09-21T07:05:02Z",
    "updated_at": "2017-03-18T14:42:12Z",
    "due_on": "2016-10-19T07:00:00Z",
    "closed_at": "2016-10-19T00:36:21Z"
  },
  "comments": 24,
  "created_at": "2016-06-19T16:11:15Z",
  "updated_at": "2018-05-08T19:28:14Z",
  "closed_at": "2016-10-27T16:27:34Z",
  "author_association": "NONE",
  "body": "I found strange behaviour using the `pipe()` method (only verified on german variant):\n\nIf you parse a document using `pipe()` you can get a ValueError, while if i use `nlp(text)` everything is fine. I boiled it down to single words, while german words work, english words like 'windows' don't work.\n\nSteps to reproduce:\n\n``` python\nimport spacy\nnlp = spacy.load('de')\ndef texts():\n    yield \"Windows\"\nfor doc in nlp.pipe(texts(), n_threads=16, batch_size=1000):\n    print(len(doc))  # doc access -> ValueError\n```\n\nTrace\n\n```\nValueError                                Traceback (most recent call last)\n<ipython-input-2-9a095ec5505b> in <module>()\n      8 def texts():\n      9     yield \"Windows\"\n---> 10 for doc in nlp.pipe(texts(), n_threads=16, batch_size=1000):\n     11     print(len(doc))\n\n.../venv/lib/python3.4/site-packages/spacy/language.py in pipe(self, texts, tag, parse, entity, n_threads, batch_size)\n    254             stream = self.entity.pipe(stream,\n    255                 n_threads=1, batch_size=batch_size)\n--> 256         for doc in stream:\n    257             yield doc\n    258 \nValueError: Error parsing doc: Windows\n```\n\nIf you use `nlp(\"Windows\")` it works fine. Also if you execute `nlp(\"Windows\")` before the same `pipe()` call, `pipe()` does not raise an exception (a dictionary is built?)\n\nVersions:\n\n```\nPython 3.4.3 (Problem not related to ipython)\nspacy 0.101.0\n```\n\nMaybe this is related to this region [syntax/parser.pyx](https://github.com/spacy-io/spaCy/blob/1822bb4ff1e6ceee76fe5e43de4345fab168e65b/spacy/syntax/parser.pyx#L179-L183)\n\n``` python\nif not eg.is_valid[guess]:\n    # with gil:\n    #     move_name = self.moves.move_name(action.move, action.label)\n    #     print 'invalid action:', move_name\n    return 1\n```\n",
  "closed_by": {
    "login": "honnibal",
    "id": 8059750,
    "node_id": "MDQ6VXNlcjgwNTk3NTA=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/8059750?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/honnibal",
    "html_url": "https://github.com/honnibal",
    "followers_url": "https://api.github.com/users/honnibal/followers",
    "following_url": "https://api.github.com/users/honnibal/following{/other_user}",
    "gists_url": "https://api.github.com/users/honnibal/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/honnibal/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/honnibal/subscriptions",
    "organizations_url": "https://api.github.com/users/honnibal/orgs",
    "repos_url": "https://api.github.com/users/honnibal/repos",
    "events_url": "https://api.github.com/users/honnibal/events{/privacy}",
    "received_events_url": "https://api.github.com/users/honnibal/received_events",
    "type": "User",
    "site_admin": false
  }
},{"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/227703099", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-227703099", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 227703099, "node_id": "MDEyOklzc3VlQ29tbWVudDIyNzcwMzA5OQ==", "user": {"login": "pdeburen", "id": 8310537, "node_id": "MDQ6VXNlcjgzMTA1Mzc=", "avatar_url": "https://avatars3.githubusercontent.com/u/8310537?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pdeburen", "html_url": "https://github.com/pdeburen", "followers_url": "https://api.github.com/users/pdeburen/followers", "following_url": "https://api.github.com/users/pdeburen/following{/other_user}", "gists_url": "https://api.github.com/users/pdeburen/gists{/gist_id}", "starred_url": "https://api.github.com/users/pdeburen/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pdeburen/subscriptions", "organizations_url": "https://api.github.com/users/pdeburen/orgs", "repos_url": "https://api.github.com/users/pdeburen/repos", "events_url": "https://api.github.com/users/pdeburen/events{/privacy}", "received_events_url": "https://api.github.com/users/pdeburen/received_events", "type": "User", "site_admin": false}, "created_at": "2016-06-22T10:19:57Z", "updated_at": "2016-06-22T10:19:57Z", "author_association": "NONE", "body": "Same issue here with the german model and `nlp.pipe()` on Amazon Linux (also on Ubuntu Server 14.04 LTS) using python 3.5. \nHowever, blang's minimal example works on my Macbook (OSX 10.11.3) where I don't have OpenMP support in place (obviously only in single-thread). Setting `n_threads=1` on Linux doesn't solve the issue for me.\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/239119709", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-239119709", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 239119709, "node_id": "MDEyOklzc3VlQ29tbWVudDIzOTExOTcwOQ==", "user": {"login": "pdeburen", "id": 8310537, "node_id": "MDQ6VXNlcjgzMTA1Mzc=", "avatar_url": "https://avatars3.githubusercontent.com/u/8310537?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pdeburen", "html_url": "https://github.com/pdeburen", "followers_url": "https://api.github.com/users/pdeburen/followers", "following_url": "https://api.github.com/users/pdeburen/following{/other_user}", "gists_url": "https://api.github.com/users/pdeburen/gists{/gist_id}", "starred_url": "https://api.github.com/users/pdeburen/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pdeburen/subscriptions", "organizations_url": "https://api.github.com/users/pdeburen/orgs", "repos_url": "https://api.github.com/users/pdeburen/repos", "events_url": "https://api.github.com/users/pdeburen/events{/privacy}", "received_events_url": "https://api.github.com/users/pdeburen/received_events", "type": "User", "site_admin": false}, "created_at": "2016-08-11T10:00:26Z", "updated_at": "2016-08-11T10:00:26Z", "author_association": "NONE", "body": "I just tried this again and it seems to work now (reinstalled spaCy and the german model). @blang can you confirm? @syllog1sm Out of curiosity: Has there been an update to the German model which fixed this? Or was it a code change?\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/240748173", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-240748173", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 240748173, "node_id": "MDEyOklzc3VlQ29tbWVudDI0MDc0ODE3Mw==", "user": {"login": "ontoport", "id": 698761, "node_id": "MDQ6VXNlcjY5ODc2MQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/698761?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ontoport", "html_url": "https://github.com/ontoport", "followers_url": "https://api.github.com/users/ontoport/followers", "following_url": "https://api.github.com/users/ontoport/following{/other_user}", "gists_url": "https://api.github.com/users/ontoport/gists{/gist_id}", "starred_url": "https://api.github.com/users/ontoport/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ontoport/subscriptions", "organizations_url": "https://api.github.com/users/ontoport/orgs", "repos_url": "https://api.github.com/users/ontoport/repos", "events_url": "https://api.github.com/users/ontoport/events{/privacy}", "received_events_url": "https://api.github.com/users/ontoport/received_events", "type": "User", "site_admin": false}, "created_at": "2016-08-18T14:52:52Z", "updated_at": "2016-08-18T15:04:55Z", "author_association": "NONE", "body": "Same problem here, working on Windows 10 with German text. Thought it was German that made it break. I also reinstalled spaCy and the German model yesterday, but this din't fix the problem in my case. I then tried to break it down to a specific sentence, but even after having removed this and succesively the follwoing sentences from my texts, the problem remained the same. \nAs above, if I use nlp(text) everything is fine.\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/244535671", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-244535671", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 244535671, "node_id": "MDEyOklzc3VlQ29tbWVudDI0NDUzNTY3MQ==", "user": {"login": "elyase", "id": 1175888, "node_id": "MDQ6VXNlcjExNzU4ODg=", "avatar_url": "https://avatars3.githubusercontent.com/u/1175888?v=4", "gravatar_id": "", "url": "https://api.github.com/users/elyase", "html_url": "https://github.com/elyase", "followers_url": "https://api.github.com/users/elyase/followers", "following_url": "https://api.github.com/users/elyase/following{/other_user}", "gists_url": "https://api.github.com/users/elyase/gists{/gist_id}", "starred_url": "https://api.github.com/users/elyase/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/elyase/subscriptions", "organizations_url": "https://api.github.com/users/elyase/orgs", "repos_url": "https://api.github.com/users/elyase/repos", "events_url": "https://api.github.com/users/elyase/events{/privacy}", "received_events_url": "https://api.github.com/users/elyase/received_events", "type": "User", "site_admin": false}, "created_at": "2016-09-03T09:00:39Z", "updated_at": "2016-09-03T09:07:43Z", "author_association": "CONTRIBUTOR", "body": "I also had this problem with english text, it looks like a parser issue. Steps to reproduce:\n\n``` python\ndef texts():\n    yield \"11th September 11 years ago I started my first business\"\n\nfor doc in nlp.pipe(texts()):\n    pass\n```\n\nraises:\n\n```\n---------------------------------------------------------------------------\nValueError                                Traceback (most recent call last)\n<ipython-input-66-a423c90922c1> in <module>()\n      3     yield \"11th September 11 years ago I started my first business\"\n      4 \n----> 5 for doc in nlp.pipe(texts()):\n      6     pass\n\n/Users/elyase/miniconda3/envs/intent/lib/python3.5/site-packages/spacy/language.py in pipe(self, texts, tag, parse, entity, n_threads, batch_size)\n    254             stream = self.entity.pipe(stream,\n    255                 n_threads=1, batch_size=batch_size)\n--> 256         for doc in stream:\n    257             yield doc\n    258 \n\n/Users/elyase/miniconda3/envs/intent/lib/python3.5/site-packages/spacy/syntax/parser.pyx in pipe (spacy/syntax/parser.cpp:7143)()\n\nValueError: Error parsing doc: 11th September 11 years ago I started my first business\n```\n\nCurious thing, If you add a comma like this:\n\n```\n\"11th September, 11 years ago I started my first business\"\n```\n\nthe error goes away. Directly doing: \n\n```\ndoc = nlp(\"11th September 11 years ago I started my first business\")\n```\n\nis ok in both cases.\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/249930995", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-249930995", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 249930995, "node_id": "MDEyOklzc3VlQ29tbWVudDI0OTkzMDk5NQ==", "user": {"login": "honnibal", "id": 8059750, "node_id": "MDQ6VXNlcjgwNTk3NTA=", "avatar_url": "https://avatars3.githubusercontent.com/u/8059750?v=4", "gravatar_id": "", "url": "https://api.github.com/users/honnibal", "html_url": "https://github.com/honnibal", "followers_url": "https://api.github.com/users/honnibal/followers", "following_url": "https://api.github.com/users/honnibal/following{/other_user}", "gists_url": "https://api.github.com/users/honnibal/gists{/gist_id}", "starred_url": "https://api.github.com/users/honnibal/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/honnibal/subscriptions", "organizations_url": "https://api.github.com/users/honnibal/orgs", "repos_url": "https://api.github.com/users/honnibal/repos", "events_url": "https://api.github.com/users/honnibal/events{/privacy}", "received_events_url": "https://api.github.com/users/honnibal/received_events", "type": "User", "site_admin": false}, "created_at": "2016-09-27T17:08:51Z", "updated_at": "2016-09-27T17:08:51Z", "author_association": "MEMBER", "body": "I think the `.pipe()` method isn't actually to blame here \u2014 rather, it reports on an error condition thrown by the `parseC` method, while the `__call__` method fails silently in the same situation. I've fixed the silent failure, so that errors will be reported more consistently, but the underlying issue is possibly tricky.\n\nThe issue is arising because the entity recogniser's push-down automaton finds itself in a state with no continuations. I haven't stepped through the automaton yet (if you want to do that, use the method`nlp.entity.step_through(doc)`) to see exactly where the problem is, but I'm pretty sure the error will come from an interaction with entities pre-set by the `Matcher` class. In order to preserve these entities, we restrict the actions of the entity recogniser, so that it can't over-write the previous ones. There's apparently a bug in the logic to introduce this constraint, that's leaving the automaton with no available actions. This results in an invalid predicted action, leading the parser to return a status code (it can't raise an error, as it's in a `nogil` function). This is the status code the `__call__` method was ignoring.\n\nI'm afraid that 1.0 might paper over this problem, because the matcher won't by default set entities anymore \u2014 this will be up to the user's control (there's a better API for customising the pipeline, though).\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/252304696", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-252304696", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 252304696, "node_id": "MDEyOklzc3VlQ29tbWVudDI1MjMwNDY5Ng==", "user": {"login": "mattilyra", "id": 1055719, "node_id": "MDQ6VXNlcjEwNTU3MTk=", "avatar_url": "https://avatars2.githubusercontent.com/u/1055719?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mattilyra", "html_url": "https://github.com/mattilyra", "followers_url": "https://api.github.com/users/mattilyra/followers", "following_url": "https://api.github.com/users/mattilyra/following{/other_user}", "gists_url": "https://api.github.com/users/mattilyra/gists{/gist_id}", "starred_url": "https://api.github.com/users/mattilyra/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mattilyra/subscriptions", "organizations_url": "https://api.github.com/users/mattilyra/orgs", "repos_url": "https://api.github.com/users/mattilyra/repos", "events_url": "https://api.github.com/users/mattilyra/events{/privacy}", "received_events_url": "https://api.github.com/users/mattilyra/received_events", "type": "User", "site_admin": false}, "created_at": "2016-10-07T16:55:21Z", "updated_at": "2016-10-08T11:29:05Z", "author_association": "NONE", "body": "This might have something to do with state between the documents (don't know what if any is kept). I was having this exact issue with the german model and decided to just randomly shuffle the corpus to see what happens. At first errors were still being produced, but after a few shuffles of the corpus to errors to my surprise went away.\n\nI'll try to produce a more reliable report of the behaviour.\n\n**update** so the error going away didn't have anything to do with `random.shuffle`. However if you take the document that produces the error, pass it through `nlp(doc)` and then call `.pipe([doc])` again, it works.\n\nAn example document where `9/11` causes the error, removing that one token everything is fine.\n\n```\ndoc = \"\"\"Nichtsdestoweniger sagen wir Ihnen zu, dass wir genauso wie bei OEF daran arbeiten werden, dass dieses Mandat eine andere Struktur erh\u00e4lt, und zwar aus politischen Gr\u00fcnden, weil zwar nicht rechtlich, aber nat\u00fcrlich politisch zur Kenntnis zu nehmen ist, dass 9/11 schon einige Zeit her ist.\"\"\"\n```\n\nTested on `0.101` and `master` - the issue seems to be fixed on `master` not just for the example document above, but for the entire corpus where that doc came from.\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/254678411", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-254678411", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 254678411, "node_id": "MDEyOklzc3VlQ29tbWVudDI1NDY3ODQxMQ==", "user": {"login": "honnibal", "id": 8059750, "node_id": "MDQ6VXNlcjgwNTk3NTA=", "avatar_url": "https://avatars3.githubusercontent.com/u/8059750?v=4", "gravatar_id": "", "url": "https://api.github.com/users/honnibal", "html_url": "https://github.com/honnibal", "followers_url": "https://api.github.com/users/honnibal/followers", "following_url": "https://api.github.com/users/honnibal/following{/other_user}", "gists_url": "https://api.github.com/users/honnibal/gists{/gist_id}", "starred_url": "https://api.github.com/users/honnibal/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/honnibal/subscriptions", "organizations_url": "https://api.github.com/users/honnibal/orgs", "repos_url": "https://api.github.com/users/honnibal/repos", "events_url": "https://api.github.com/users/honnibal/events{/privacy}", "received_events_url": "https://api.github.com/users/honnibal/received_events", "type": "User", "site_admin": false}, "created_at": "2016-10-19T00:34:29Z", "updated_at": "2016-10-19T00:34:29Z", "author_association": "MEMBER", "body": "I think I have this taken care of, but I'm not 100% sure. Please reopen if it reoccurs.\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/256633721", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-256633721", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 256633721, "node_id": "MDEyOklzc3VlQ29tbWVudDI1NjYzMzcyMQ==", "user": {"login": "sadovnychyi", "id": 193864, "node_id": "MDQ6VXNlcjE5Mzg2NA==", "avatar_url": "https://avatars3.githubusercontent.com/u/193864?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sadovnychyi", "html_url": "https://github.com/sadovnychyi", "followers_url": "https://api.github.com/users/sadovnychyi/followers", "following_url": "https://api.github.com/users/sadovnychyi/following{/other_user}", "gists_url": "https://api.github.com/users/sadovnychyi/gists{/gist_id}", "starred_url": "https://api.github.com/users/sadovnychyi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sadovnychyi/subscriptions", "organizations_url": "https://api.github.com/users/sadovnychyi/orgs", "repos_url": "https://api.github.com/users/sadovnychyi/repos", "events_url": "https://api.github.com/users/sadovnychyi/events{/privacy}", "received_events_url": "https://api.github.com/users/sadovnychyi/received_events", "type": "User", "site_admin": false}, "created_at": "2016-10-27T13:00:04Z", "updated_at": "2016-10-27T13:00:04Z", "author_association": "CONTRIBUTOR", "body": "FYI it did happen for me with 1.1.0, but so far I cannot provide any steps to reproduce it.\n\nThe text it tried to parse isn't relevant: `Waiver of Jury Trial` but I did update global `nlp.matcher` in a loop while parsing the doc in the same loop. I'll get back to this if I'll be able to reproduce it with specific steps. \n\nPS: Now I'm getting `Segmentation fault: 11` and I have no idea if it's relevant or not.. \n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/256634895", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-256634895", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 256634895, "node_id": "MDEyOklzc3VlQ29tbWVudDI1NjYzNDg5NQ==", "user": {"login": "honnibal", "id": 8059750, "node_id": "MDQ6VXNlcjgwNTk3NTA=", "avatar_url": "https://avatars3.githubusercontent.com/u/8059750?v=4", "gravatar_id": "", "url": "https://api.github.com/users/honnibal", "html_url": "https://github.com/honnibal", "followers_url": "https://api.github.com/users/honnibal/followers", "following_url": "https://api.github.com/users/honnibal/following{/other_user}", "gists_url": "https://api.github.com/users/honnibal/gists{/gist_id}", "starred_url": "https://api.github.com/users/honnibal/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/honnibal/subscriptions", "organizations_url": "https://api.github.com/users/honnibal/orgs", "repos_url": "https://api.github.com/users/honnibal/repos", "events_url": "https://api.github.com/users/honnibal/events{/privacy}", "received_events_url": "https://api.github.com/users/honnibal/received_events", "type": "User", "site_admin": false}, "created_at": "2016-10-27T13:05:23Z", "updated_at": "2016-10-27T13:05:23Z", "author_association": "MEMBER", "body": "Do you have a minute to video chat about this? If so click here:\n\nhttps://appear.in/spacy_issue429 \n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/256635380", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-256635380", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 256635380, "node_id": "MDEyOklzc3VlQ29tbWVudDI1NjYzNTM4MA==", "user": {"login": "sadovnychyi", "id": 193864, "node_id": "MDQ6VXNlcjE5Mzg2NA==", "avatar_url": "https://avatars3.githubusercontent.com/u/193864?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sadovnychyi", "html_url": "https://github.com/sadovnychyi", "followers_url": "https://api.github.com/users/sadovnychyi/followers", "following_url": "https://api.github.com/users/sadovnychyi/following{/other_user}", "gists_url": "https://api.github.com/users/sadovnychyi/gists{/gist_id}", "starred_url": "https://api.github.com/users/sadovnychyi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sadovnychyi/subscriptions", "organizations_url": "https://api.github.com/users/sadovnychyi/orgs", "repos_url": "https://api.github.com/users/sadovnychyi/repos", "events_url": "https://api.github.com/users/sadovnychyi/events{/privacy}", "received_events_url": "https://api.github.com/users/sadovnychyi/received_events", "type": "User", "site_admin": false}, "created_at": "2016-10-27T13:07:34Z", "updated_at": "2016-10-27T13:07:34Z", "author_association": "CONTRIBUTOR", "body": "Sorry, my internet isn't good for video chatting, but I'm happy to text.\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/256636268", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-256636268", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 256636268, "node_id": "MDEyOklzc3VlQ29tbWVudDI1NjYzNjI2OA==", "user": {"login": "honnibal", "id": 8059750, "node_id": "MDQ6VXNlcjgwNTk3NTA=", "avatar_url": "https://avatars3.githubusercontent.com/u/8059750?v=4", "gravatar_id": "", "url": "https://api.github.com/users/honnibal", "html_url": "https://github.com/honnibal", "followers_url": "https://api.github.com/users/honnibal/followers", "following_url": "https://api.github.com/users/honnibal/following{/other_user}", "gists_url": "https://api.github.com/users/honnibal/gists{/gist_id}", "starred_url": "https://api.github.com/users/honnibal/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/honnibal/subscriptions", "organizations_url": "https://api.github.com/users/honnibal/orgs", "repos_url": "https://api.github.com/users/honnibal/repos", "events_url": "https://api.github.com/users/honnibal/events{/privacy}", "received_events_url": "https://api.github.com/users/honnibal/received_events", "type": "User", "site_admin": false}, "created_at": "2016-10-27T13:11:26Z", "updated_at": "2016-10-27T13:11:36Z", "author_association": "MEMBER", "body": "No worries.\n\nIf you're getting a segfault the handiest thing to do would be to break out the pipeline manually. Instead of:\n\n```\ndoc = nlp(text)\n```\n\nYou can do:\n\n```\ndoc = nlp.tokenizer(text)\nnlp.tagger(doc)\nnlp.parser(doc)\nnlp.entity(doc)\nmatches = nlp.matcher(doc)\n# Act on your matches\n```\n\nThen you can investigate what's going on.\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/256637137", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-256637137", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 256637137, "node_id": "MDEyOklzc3VlQ29tbWVudDI1NjYzNzEzNw==", "user": {"login": "sadovnychyi", "id": 193864, "node_id": "MDQ6VXNlcjE5Mzg2NA==", "avatar_url": "https://avatars3.githubusercontent.com/u/193864?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sadovnychyi", "html_url": "https://github.com/sadovnychyi", "followers_url": "https://api.github.com/users/sadovnychyi/followers", "following_url": "https://api.github.com/users/sadovnychyi/following{/other_user}", "gists_url": "https://api.github.com/users/sadovnychyi/gists{/gist_id}", "starred_url": "https://api.github.com/users/sadovnychyi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sadovnychyi/subscriptions", "organizations_url": "https://api.github.com/users/sadovnychyi/orgs", "repos_url": "https://api.github.com/users/sadovnychyi/repos", "events_url": "https://api.github.com/users/sadovnychyi/events{/privacy}", "received_events_url": "https://api.github.com/users/sadovnychyi/received_events", "type": "User", "site_admin": false}, "created_at": "2016-10-27T13:14:52Z", "updated_at": "2016-10-27T13:14:52Z", "author_association": "CONTRIBUTOR", "body": "The segfault is caused by matcher. The number of matches I have is up to a million, python process eats about 4 GB of ram, and there's still enough for it to grow. I could investigate this later, maybe in another issue.\n\nTrying to narrow the scope of ParserStateError right now.\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/256637564", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-256637564", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 256637564, "node_id": "MDEyOklzc3VlQ29tbWVudDI1NjYzNzU2NA==", "user": {"login": "honnibal", "id": 8059750, "node_id": "MDQ6VXNlcjgwNTk3NTA=", "avatar_url": "https://avatars3.githubusercontent.com/u/8059750?v=4", "gravatar_id": "", "url": "https://api.github.com/users/honnibal", "html_url": "https://github.com/honnibal", "followers_url": "https://api.github.com/users/honnibal/followers", "following_url": "https://api.github.com/users/honnibal/following{/other_user}", "gists_url": "https://api.github.com/users/honnibal/gists{/gist_id}", "starred_url": "https://api.github.com/users/honnibal/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/honnibal/subscriptions", "organizations_url": "https://api.github.com/users/honnibal/orgs", "repos_url": "https://api.github.com/users/honnibal/repos", "events_url": "https://api.github.com/users/honnibal/events{/privacy}", "received_events_url": "https://api.github.com/users/honnibal/received_events", "type": "User", "site_admin": false}, "created_at": "2016-10-27T13:16:45Z", "updated_at": "2016-10-27T13:16:45Z", "author_association": "MEMBER", "body": "Hmm. Is the match proliferation expected for your use-case?\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/256642451", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-256642451", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 256642451, "node_id": "MDEyOklzc3VlQ29tbWVudDI1NjY0MjQ1MQ==", "user": {"login": "sadovnychyi", "id": 193864, "node_id": "MDQ6VXNlcjE5Mzg2NA==", "avatar_url": "https://avatars3.githubusercontent.com/u/193864?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sadovnychyi", "html_url": "https://github.com/sadovnychyi", "followers_url": "https://api.github.com/users/sadovnychyi/followers", "following_url": "https://api.github.com/users/sadovnychyi/following{/other_user}", "gists_url": "https://api.github.com/users/sadovnychyi/gists{/gist_id}", "starred_url": "https://api.github.com/users/sadovnychyi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sadovnychyi/subscriptions", "organizations_url": "https://api.github.com/users/sadovnychyi/orgs", "repos_url": "https://api.github.com/users/sadovnychyi/repos", "events_url": "https://api.github.com/users/sadovnychyi/events{/privacy}", "received_events_url": "https://api.github.com/users/sadovnychyi/received_events", "type": "User", "site_admin": false}, "created_at": "2016-10-27T13:36:26Z", "updated_at": "2016-10-27T13:39:48Z", "author_association": "CONTRIBUTOR", "body": "``` python\nimport spacy\nfrom spacy.attrs import ORTH\n\nnlp = spacy.load('en')\n\n\ndef merge_phrases(matcher, doc, i, matches):\n  if i != len(matches) - 1:\n    return None\n  spans = [(ent_id, label, doc[start:end]) for ent_id, label, start, end in matches]\n  for ent_id, label, span in spans:\n    span.merge('NNP' if label else span.root.tag_, span.text, nlp.vocab.strings[label])\n\ndoc = nlp('a')\nnlp.matcher.add('key', label='TEST', attrs={}, specs=[[{ORTH: 'a'}]], on_match=merge_phrases)\ndoc = nlp('a b')\n```\n\n->\n\n```\nTraceback (most recent call last):                                                          \n  File \"case.py\", line 17, in <module>\n    doc = nlp('a b')\n  File \"/usr/local/lib/python3.5/site-packages/spacy/language.py\", line 313, in __call__\n    proc(doc)\n  File \"spacy/syntax/parser.pyx\", line 117, in spacy.syntax.parser.Parser.__call__ (spacy/syntax/parser.cpp:6104)\nspacy.syntax.parser.ParserStateError: Error analysing doc -- no valid actions available. This should never happen, so please report the error on the issue tracker. Here's the thread to do so --- reopen it if it's closed:\nhttps://github.com/spacy-io/spaCy/issues/429\nPlease include the text that the parser failed on, which is:\n'a b'\n```\n\nre: Hmm. Is the match proliferation expected for your use-case?\nIt won't grow much after this, I'm just curious how much entities it can hold and how it will affect the memory and performance. Should I open another issue for that segfault? \n\n```\n>>> spacy.about.__version__\n'1.1.2'\n```\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/256644729", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-256644729", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 256644729, "node_id": "MDEyOklzc3VlQ29tbWVudDI1NjY0NDcyOQ==", "user": {"login": "honnibal", "id": 8059750, "node_id": "MDQ6VXNlcjgwNTk3NTA=", "avatar_url": "https://avatars3.githubusercontent.com/u/8059750?v=4", "gravatar_id": "", "url": "https://api.github.com/users/honnibal", "html_url": "https://github.com/honnibal", "followers_url": "https://api.github.com/users/honnibal/followers", "following_url": "https://api.github.com/users/honnibal/following{/other_user}", "gists_url": "https://api.github.com/users/honnibal/gists{/gist_id}", "starred_url": "https://api.github.com/users/honnibal/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/honnibal/subscriptions", "organizations_url": "https://api.github.com/users/honnibal/orgs", "repos_url": "https://api.github.com/users/honnibal/repos", "events_url": "https://api.github.com/users/honnibal/events{/privacy}", "received_events_url": "https://api.github.com/users/honnibal/received_events", "type": "User", "site_admin": false}, "created_at": "2016-10-27T13:45:02Z", "updated_at": "2016-10-27T14:29:10Z", "author_association": "MEMBER", "body": "> It won't grow much after this, I'm just curious how much entities it can hold and how it will affect the memory and performance. Should I open another issue for that segfault?\n\nI can easily make the matches list a numpy array if necessary.\n\nA segfault via the Python API (as opposed to the Cython API) is always a bug. So yes, please open an issue.\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/256678481", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-256678481", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 256678481, "node_id": "MDEyOklzc3VlQ29tbWVudDI1NjY3ODQ4MQ==", "user": {"login": "sadovnychyi", "id": 193864, "node_id": "MDQ6VXNlcjE5Mzg2NA==", "avatar_url": "https://avatars3.githubusercontent.com/u/193864?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sadovnychyi", "html_url": "https://github.com/sadovnychyi", "followers_url": "https://api.github.com/users/sadovnychyi/followers", "following_url": "https://api.github.com/users/sadovnychyi/following{/other_user}", "gists_url": "https://api.github.com/users/sadovnychyi/gists{/gist_id}", "starred_url": "https://api.github.com/users/sadovnychyi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sadovnychyi/subscriptions", "organizations_url": "https://api.github.com/users/sadovnychyi/orgs", "repos_url": "https://api.github.com/users/sadovnychyi/repos", "events_url": "https://api.github.com/users/sadovnychyi/events{/privacy}", "received_events_url": "https://api.github.com/users/sadovnychyi/received_events", "type": "User", "site_admin": false}, "created_at": "2016-10-27T15:36:12Z", "updated_at": "2016-10-27T15:36:12Z", "author_association": "CONTRIBUTOR", "body": "I'll do it tomorrow, once I know the steps to reproduce it.\n\nI guess now you have enough info for bug related to current issue.\n\nOn Thu, Oct 27, 2016, 21:45 Matthew Honnibal notifications@github.com\nwrote:\n\n> It won't grow much after this, I'm just curious how much entities it can\n> hold and how it will affect the memory and performance. Should I open\n> another issue for that segfault?\n> \n> I can easily make the matches list a C++ vector if necessary.\n> \n> A segfault via the Python API (as opposed to the Cython API) is always a\n> bug. So yes, please open an issue.\n> \n> \u2014\n> You are receiving this because you commented.\n> Reply to this email directly, view it on GitHub\n> https://github.com/explosion/spaCy/issues/429#issuecomment-256644729,\n> or mute the thread\n> https://github.com/notifications/unsubscribe-auth/AAL1SKptmaW0BE-yVBdMd5POkfwfMSTQks5q4KrkgaJpZM4I5Mhy\n> .\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/256686697", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-256686697", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 256686697, "node_id": "MDEyOklzc3VlQ29tbWVudDI1NjY4NjY5Nw==", "user": {"login": "honnibal", "id": 8059750, "node_id": "MDQ6VXNlcjgwNTk3NTA=", "avatar_url": "https://avatars3.githubusercontent.com/u/8059750?v=4", "gravatar_id": "", "url": "https://api.github.com/users/honnibal", "html_url": "https://github.com/honnibal", "followers_url": "https://api.github.com/users/honnibal/followers", "following_url": "https://api.github.com/users/honnibal/following{/other_user}", "gists_url": "https://api.github.com/users/honnibal/gists{/gist_id}", "starred_url": "https://api.github.com/users/honnibal/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/honnibal/subscriptions", "organizations_url": "https://api.github.com/users/honnibal/orgs", "repos_url": "https://api.github.com/users/honnibal/repos", "events_url": "https://api.github.com/users/honnibal/events{/privacy}", "received_events_url": "https://api.github.com/users/honnibal/received_events", "type": "User", "site_admin": false}, "created_at": "2016-10-27T15:53:59Z", "updated_at": "2016-10-27T15:53:59Z", "author_association": "MEMBER", "body": "Yes. I have the test set up and I'm pretty sure I understand the problem now. Fix should be out soon.\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/256696762", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-256696762", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 256696762, "node_id": "MDEyOklzc3VlQ29tbWVudDI1NjY5Njc2Mg==", "user": {"login": "honnibal", "id": 8059750, "node_id": "MDQ6VXNlcjgwNTk3NTA=", "avatar_url": "https://avatars3.githubusercontent.com/u/8059750?v=4", "gravatar_id": "", "url": "https://api.github.com/users/honnibal", "html_url": "https://github.com/honnibal", "followers_url": "https://api.github.com/users/honnibal/followers", "following_url": "https://api.github.com/users/honnibal/following{/other_user}", "gists_url": "https://api.github.com/users/honnibal/gists{/gist_id}", "starred_url": "https://api.github.com/users/honnibal/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/honnibal/subscriptions", "organizations_url": "https://api.github.com/users/honnibal/orgs", "repos_url": "https://api.github.com/users/honnibal/repos", "events_url": "https://api.github.com/users/honnibal/events{/privacy}", "received_events_url": "https://api.github.com/users/honnibal/received_events", "type": "User", "site_admin": false}, "created_at": "2016-10-27T16:27:10Z", "updated_at": "2016-10-27T16:27:32Z", "author_association": "MEMBER", "body": "I think this should fix the segfault too \u2014 I think they were related.\n\nClosing for now. Again, if it reoccurs, don't hesitate to reopen :)\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/269842440", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-269842440", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 269842440, "node_id": "MDEyOklzc3VlQ29tbWVudDI2OTg0MjQ0MA==", "user": {"login": "paulkarpenko", "id": 2983780, "node_id": "MDQ6VXNlcjI5ODM3ODA=", "avatar_url": "https://avatars0.githubusercontent.com/u/2983780?v=4", "gravatar_id": "", "url": "https://api.github.com/users/paulkarpenko", "html_url": "https://github.com/paulkarpenko", "followers_url": "https://api.github.com/users/paulkarpenko/followers", "following_url": "https://api.github.com/users/paulkarpenko/following{/other_user}", "gists_url": "https://api.github.com/users/paulkarpenko/gists{/gist_id}", "starred_url": "https://api.github.com/users/paulkarpenko/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/paulkarpenko/subscriptions", "organizations_url": "https://api.github.com/users/paulkarpenko/orgs", "repos_url": "https://api.github.com/users/paulkarpenko/repos", "events_url": "https://api.github.com/users/paulkarpenko/events{/privacy}", "received_events_url": "https://api.github.com/users/paulkarpenko/received_events", "type": "User", "site_admin": false}, "created_at": "2016-12-31T01:38:38Z", "updated_at": "2016-12-31T18:11:04Z", "author_association": "NONE", "body": "UPDATE: I was able to get around this by converting multiple spaces to a single space. Not sure if this was an issue with my string or with spaCy's processing.\r\n\r\n@honnibal A spaCy error told me to reopen this thread :-/ Not sure I have the rights to do that, but here's the text:\r\n\r\n```\r\nFile \"spacy/syntax/parser.pyx\", line 146, in spacy.syntax.parser.Parser.__call__ (spacy/syntax/parser.cpp:6114)\r\nspacy.syntax.parser.ParserStateError: Error analysing doc -- no valid actions available. This should never happen, so please report the error on the issue tracker. Here's the thread to do so --- reopen it if it's closed:\r\nhttps://github.com/spacy-io/spaCy/issues/429\r\nPlease include the text that the parser failed on, which is:\r\n'The 2016 election has been all about Donald Trump \u2014 even down ballot. His campaign has had a huge effect on the battle for the House, driving the two-year string of events that led us to Election Day. Here are the 16 moments that defined the 2016 race for the House. 1. House Republicans stretch their majority to historic proportions in 2014If Republicans hadn\u2019t expanded their majority to a whopping 30 seats in 2014, who knows what position they would be in today. But by winning their biggest majority since 1928 that year, the GOP stretched Democrats\u2019 resources over a large 2016 battlefield packed with incumbents, who largely ran strong campaigns. Even at their best moments this campaign, Democrats have been reluctant to say they could challenge for the majority, and the 2014 election is a big reason why. 2. Judges torpedo Florida\u2019s congressional mapOne reason Democrats are sure to make gains in the House this year is that courts in several states ordered re-draws of several gerrymandered congressional maps. Florida\u2019s was the biggest: The new version of the map turned one Democratic district Republican, but it also tilted two GOP-held districts decisively Democratic, made a Republican-held battleground seat more Democratic-leaning, and put another veteran GOP lawmaker in a swing district for the first time. Democrats also gained a seat from court-ordered redistricting in Virginia, while several incumbents in both states and North Carolina lost primary challenges because they were put in new territory. 3. Trump\u2019s Super Tuesday win fuels Democratic recruiting surgeThough Democrats have mostly been realistic about their chances of winning the House majority this year, Trump\u2019s success in the GOP presidential race brought with it a surge of optimism \u2014 and new candidates. Starting in early April, a handful of Democrats who would go on to become real threats to beat GOP incumbents launched late House campaigns in Colorado, Florida, Kansas, and more. A number of them, like Minnesota\u2019s Terri Bonoff, cited Trump as a factor in their decisions to run \u2014 and later made him a focus of their advertising against local incumbents. 4. The House Freedom Caucus takes John Boehner\u2019s congressional districtThe hard-line House Freedom Caucus helped force Speaker John Boehner\u2019s resignation in 2015, and then it added a symbolic insult to the establishment\u2019s injury in March, when HFC-endorsed candidate Warren Davidson won the GOP primary to take over Boehner\u2019s seat. The Freedom Caucus is sure to have continued influence in the House GOP Conference \u2014 with its numbers staying steady around 40 while the overall size of the Republican majority shrinks \u2014 and Davidson\u2019s win was a big wakeup call to establishment donors that they were getting caught sleeping in the primaries that determined the makeup of their majority. 5. Democrats leave districts on the table in the springWhile Trump did help the party turn more House seats into battlegrounds this fall, Democrats also failed to get viable candidates in some districts that could have gotten interesting. An April primary in the Philadelphia suburbs ended in embarrassing defeat for one DCCC-backed candidate, while the victor has raised little money since. Other seats in New Mexico, southeastern Virginia, New Jersey, and more \u2014 where Democrats have made strong challenges in the past \u2014 fell by the wayside without strong candidates. 6. Donald Trump becomes the presumptive Republican presidential nomineeIt all starts with Trump. More than any other members of their party except Hillary Clinton, House Democrats have tried to make their local campaigns about the GOP nominee. Trump has fueled an \u201ceducation gap\u201d between the parties, which has endangered Republican House members in white-collar suburbs that were once safer for the GOP \u2014 but also shored up Republicans in blue-collar swing districts in the Northeast and Midwest. Veteran incumbents on both sides (including GOP Reps. Darrell Issa outside San Diego and John Mica outside Orlando, as well as northeastern Minnesota Democrat Rick Nolan) could fall victim to this trend. 7. Paul Ryan delays on endorsing TrumpThe House speaker eventually gave the GOP presidential nominee his support, but Ryan\u2019s delay set the stage for a half-year of separation from the top of the ticket. Ryan\u2019s touting of a \u201cBetter Way\u201d helped give House Republicans cover and maneuverability with regard to Trump, as many sought to out-run him by significant margins in their districts to win reelection. Ryan also helped GOP candidates in a big way by raising more than $35 million for the NRCC as part of over $50 million overall to protect the Republican majority. 8. California (and Latinos) sprint from the GOPWhile Hillary Clinton no doubt would have liked to wrap up the Democratic presidential nomination long before California\u2019s June 7 primary, the late contest between her and Bernie Sanders fueled a voter registration surge in the state that may pay huge dividends in the fall. After initially looking to gain seats in California this year, House Republicans are now on defense in at least three toss-up districts in the state, where about 2.3 million new voters registered before the primary, including large numbers of Democratic-leaning Latinos and young voters. That state alone could put a dent in the GOP majority on Nov. 8, and increasing Latino turnout in Florida, Nevada, and several other states could net yet more Democratic districts, too. 9. Bernie Sanders makes his presence felt down-ballotWhile Sanders\u2019 presidential campaign fell short, the donor base he established became a huge boon for some House Democrats. Starting in April, Sanders has endorsed a handful of candidates around the country and raised hundreds of thousands of dollars for them by emailing his fundraising list on their behalf. That\u2019s huge money in House races, especially primaries. It helped some candidates win nominations and made others competitive where otherwise they would not have been able to run TV ads. And in the fall, Sanders-raised money helped plug holes in some House Democrats\u2019 budgets when GOP attacks arrived in their districts before backup from Democratic outside groups.  10. Roger Marshall defeats HFC member Tim Huelskamp in a Kansas primaryUsually it\u2019s the tea party that unseats GOP incumbents in primaries, but challenges to veteran Reps. Bill Shuster, Kevin Brady, and more fell short in 2016. Meanwhile, Kansas physician Roger Marshall beat GOP Rep. Tim Huelskamp by arguing that Huelskamp\u2019s tea-party positions had made him an ineffective advocate for the state\u2019s agriculture-heavy \u201cBig First\u201d district. With backup from the U.S. Chamber of Commerce and several \u201cestablishment\u201d-aligned super PACs, Marshall will take over the safe Republican seat in January. The outside groups that backed him also helped defeat potential Freedom Caucus members in two late, open GOP primaries. But it may also provoke a response from the Freedom Caucus and other conservative groups who now feel targeted by establishment donors. The 2018 GOP primaries may come with fireworks. 11. The DCCC uses Trump to send extra cash to candidatesOne side effect of Democrats\u2019 late-breaking House optimism this year was that some of their most important candidates were low on funds, whether because they started campaigns late or donors were slow to take notice. So around the end of summer and beginning of fall, those candidates started airing specially worded TV ads connecting local candidates to national Republicans and Donald Trump \u2014 and splitting hundreds of thousands of dollars each in advertising costs with the DCCC. By the last week of the election, the DCCC and at least 29 candidates had split over $14.2 million in coordinated advertising costs. The Democratic committee has not explained its legal reasoning on the Trump-focused ads, but the end result is that the party sent millions of extra dollars to candidates who might otherwise have not been able to run viable campaigns. 12. Trump\u2019s 2005 Access Hollywood tape publishesAfter tape leaked of Trump making vulgar comments about sexually assaulting women, it looked like the bottom might fall out for down-ballot Republicans. Democratic groups began pushing money into new districts, and House Republicans foresaw not only a collapse in Trump\u2019s numbers (which continued through the debates) but the potential that their base would stay home on Election Day. It was a doomsday scenario that had Democrats and Republicans alike suddenly scanning the horizon for a wave. 13. Republican super PACs douse potential fires with late moneyWhen things started to look bad for the congressional GOP in early October, House Republicans\u2019 biggest super PAC was there to fight the fire. Congressional Leadership Fund and its sister nonprofit, American Action Network, dumped $10 million into races where Democrats could have expanded the map right after the Access Hollywood tape broke, giving cover and a financial advantage to some Republican incumbents worried the national tide was about to turn against them. 14. Obama goes all-inPresident Barack Obama has not played a big role for individual Democratic House candidates while in the White House. In 2012, he was concentrating on his own reelection, and he was not popular in swing districts during the 2010 and 2014 midterms. But Obama made endorsements and cut TV and radio ads in dozens of districts in mid-October, looking to push the House in Democrats\u2019 direction as part of his political legacy. Keen observers took note that the president\u2019s first House ad of the general election backed Illinois Democrat Brad Schneider, a candidate who had opposed the White House\u2019s nuclear deal with Iran during his primary (before grudgingly coming around). It was a welcome sign for House Democrats looking to make final pushes against better-known incumbents. 15. GOP starts \u201ccheck and balance\u201d strategy against Clinton and House DemocratsAs Trump\u2019s prospects faded in October, Republican candidates and committees increasingly began running ads basically admitting that Clinton would win the White House \u2014 and arguing that voters should elect Republican House members to keep her in check. The ads weren\u2019t as widespread as in 1996, when congressional Republicans largely abandoned Bob Dole at the end of the presidential race. But Clinton\u2019s popularity was never high this election, and Republicans believed the strategy would help them hold districts against Democratic candidates about whom voters knew relatively little. 16. The FBI announces it is still looking into Clinton-related emailsAn October surprise and bookend to the Trump tape, the FBI\u2019s late email announcement helped re-energize the Republican base and, strategists believed, foreclosed on that possibility of bad turnout because of Trump\u2019s early-October struggles. It also halted House Democratic momentum just as the party was trying to expand the battleground map late."}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/273997448", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-273997448", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 273997448, "node_id": "MDEyOklzc3VlQ29tbWVudDI3Mzk5NzQ0OA==", "user": {"login": "muthupl", "id": 5379591, "node_id": "MDQ6VXNlcjUzNzk1OTE=", "avatar_url": "https://avatars3.githubusercontent.com/u/5379591?v=4", "gravatar_id": "", "url": "https://api.github.com/users/muthupl", "html_url": "https://github.com/muthupl", "followers_url": "https://api.github.com/users/muthupl/followers", "following_url": "https://api.github.com/users/muthupl/following{/other_user}", "gists_url": "https://api.github.com/users/muthupl/gists{/gist_id}", "starred_url": "https://api.github.com/users/muthupl/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/muthupl/subscriptions", "organizations_url": "https://api.github.com/users/muthupl/orgs", "repos_url": "https://api.github.com/users/muthupl/repos", "events_url": "https://api.github.com/users/muthupl/events{/privacy}", "received_events_url": "https://api.github.com/users/muthupl/received_events", "type": "User", "site_admin": false}, "created_at": "2017-01-20T07:38:52Z", "updated_at": "2017-01-20T07:38:52Z", "author_association": "NONE", "body": "Hi,\r\n\r\nWe are getting a parser state error. Here is the trace:\r\n\r\nTraceback (most recent call last):\r\n  File \"tests/test_spacy_nlp.py\", line 231, in test_should_return_none_when_spacy_parsing_fails\r\n    doc = self.spacy_nlp.parse(query)\r\n  File \"spacy_nlp.py\", line 49, in parse\r\n    return SpacyDoc(self.__instance.parser(query))\r\n  File \"lib/python3.5/site-packages/spacy/language.py\", line 328, in __call__\r\n    proc(doc)\r\n  File \"spacy/syntax/parser.pyx\", line 146, in spacy.syntax.parser.Parser.__call__ (spacy/syntax/parser.cpp:6114)\r\nspacy.syntax.parser.ParserStateError: Error analysing doc -- no valid actions available. This should never happen, so please report the error on the issue tracker. Here's the thread to do so --- reopen it if it's closed:\r\nhttps://github.com/spacy-io/spaCy/issues/429\r\nPlease include the text that the parser failed on, which is:\r\n'splash On'\r\n\r\nHere is our test:\r\nnlp = spacy.en.English()\r\nnlp.matcher.add('splash', 'my entity', {},[ [{LEMMA: 'splash'}, {LEMMA: 'on'}]])\r\nnlp('splash On')\r\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/276798881", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-276798881", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 276798881, "node_id": "MDEyOklzc3VlQ29tbWVudDI3Njc5ODg4MQ==", "user": {"login": "ejschoen", "id": 10605666, "node_id": "MDQ6VXNlcjEwNjA1NjY2", "avatar_url": "https://avatars3.githubusercontent.com/u/10605666?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ejschoen", "html_url": "https://github.com/ejschoen", "followers_url": "https://api.github.com/users/ejschoen/followers", "following_url": "https://api.github.com/users/ejschoen/following{/other_user}", "gists_url": "https://api.github.com/users/ejschoen/gists{/gist_id}", "starred_url": "https://api.github.com/users/ejschoen/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ejschoen/subscriptions", "organizations_url": "https://api.github.com/users/ejschoen/orgs", "repos_url": "https://api.github.com/users/ejschoen/repos", "events_url": "https://api.github.com/users/ejschoen/events{/privacy}", "received_events_url": "https://api.github.com/users/ejschoen/received_events", "type": "User", "site_admin": false}, "created_at": "2017-02-01T22:08:54Z", "updated_at": "2017-02-01T22:08:54Z", "author_association": "NONE", "body": "I'm afraid I'm getting this, too, in version 1.5.0:\r\n\r\n```\r\n File \"nlp.py\", line 166, in parse_sentence\r\n    doc = nlp(sentence)\r\n  File \"/usr/local/lib/python3.4/dist-packages/spacy/language.py\", line 328, in __call__\r\n    proc(doc)\r\n  File \"spacy/syntax/parser.pyx\", line 146, in spacy.syntax.parser.Parser.__call__ (spacy/syntax/parser.cpp:6114)\r\nspacy.syntax.parser.ParserStateError: Error analysing doc -- no valid actions available. This should never happen, so please report the error on the issue tracker. Here's the thread to do so --- reopen it if it's closed:\r\nhttps://github.com/spacy-io/spaCy/issues/429\r\nPlease include the text that the parser failed on, which is:\r\n'Located 16 km southwest of the Ceres find, the Hebe-1 well tested at 5,956 BOPD.'\r\n```\r\n\r\nAll was fine, until I added some matcher rules and an on_match callback:\r\n\r\n```\r\ndef unit_match_cb(matcher,doc,i,matches):\r\n    spans = [(ent_id, label, doc[start:end]) for ent_id,label,start,end in matches]\r\n    for ent_id, label, span in spans:\r\n        print(span, span[len(span)-1].tag)\r\n        span.merge(label=label, ent_type='QUANTITY', tag='NNP')\r\n\r\n\r\ndef add_uom_match(matcher, unit):\r\n    matcher.add_entity(unit, {\"ent_type\": \"QUANTITY\"}, on_match=unit_match_cb)\r\n    matcher.add_pattern(unit, [{\"like_num\":True},{ORTH: unit}], label=\"SPE_UOM\")\r\n    matcher.add_pattern(unit, [{\"like_num\":True},{ORTH: unit+\".\"}], label=\"SPE_UOM\")\r\n    matcher.add_pattern(unit, [{\"like_num\":True},{ORTH: unit+\",\"}], label=\"SPE_UOM\")\r\n    matcher.add_pattern(unit, [{\"like_num\":True},{ORTH: unit+\";\"}], label=\"SPE_UOM\")\r\n```\r\nwhere unit is 'BOPD', for example.  The on_match callback is being called.\r\n"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/298211589", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-298211589", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 298211589, "node_id": "MDEyOklzc3VlQ29tbWVudDI5ODIxMTU4OQ==", "user": {"login": "kyao", "id": 1087657, "node_id": "MDQ6VXNlcjEwODc2NTc=", "avatar_url": "https://avatars3.githubusercontent.com/u/1087657?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kyao", "html_url": "https://github.com/kyao", "followers_url": "https://api.github.com/users/kyao/followers", "following_url": "https://api.github.com/users/kyao/following{/other_user}", "gists_url": "https://api.github.com/users/kyao/gists{/gist_id}", "starred_url": "https://api.github.com/users/kyao/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kyao/subscriptions", "organizations_url": "https://api.github.com/users/kyao/orgs", "repos_url": "https://api.github.com/users/kyao/repos", "events_url": "https://api.github.com/users/kyao/events{/privacy}", "received_events_url": "https://api.github.com/users/kyao/received_events", "type": "User", "site_admin": false}, "created_at": "2017-04-30T05:03:37Z", "updated_at": "2017-04-30T05:03:37Z", "author_association": "NONE", "body": "Got this error in version 1.7.3:\r\n\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/home/ktyao/anaconda3/envs/python27/lib/python2.7/site-packages/spacy/language.py\", line 350, in __call__\r\n    proc(doc)\r\n  File \"spacy/syntax/parser.pyx\", line 207, in spacy.syntax.parser.Parser.__call__ (spacy/syntax/parser.cpp:7730)\r\nspacy.syntax.parser.ParserStateError: Error analysing doc -- no valid actions available. This should never happen, so please report the error on the issue tracker. Here's the thread to do so --- reopen it if it's closed:\r\nhttps://github.com/spacy-io/spaCy/issues/429                                                                                                                                                                                           \r\nPlease include the text that the parser failed on, which is:                                                                                                                                                                           \r\nu'Meet Linux.Mirai Trojan, a DDoS nightmare'\r\n\r\nI am using a customized tokenizer that merges the three tokens, 'Linux', '.' and 'Mirai', into one token."}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/310289853", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-310289853", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 310289853, "node_id": "MDEyOklzc3VlQ29tbWVudDMxMDI4OTg1Mw==", "user": {"login": "fsonntag", "id": 1186111, "node_id": "MDQ6VXNlcjExODYxMTE=", "avatar_url": "https://avatars3.githubusercontent.com/u/1186111?v=4", "gravatar_id": "", "url": "https://api.github.com/users/fsonntag", "html_url": "https://github.com/fsonntag", "followers_url": "https://api.github.com/users/fsonntag/followers", "following_url": "https://api.github.com/users/fsonntag/following{/other_user}", "gists_url": "https://api.github.com/users/fsonntag/gists{/gist_id}", "starred_url": "https://api.github.com/users/fsonntag/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/fsonntag/subscriptions", "organizations_url": "https://api.github.com/users/fsonntag/orgs", "repos_url": "https://api.github.com/users/fsonntag/repos", "events_url": "https://api.github.com/users/fsonntag/events{/privacy}", "received_events_url": "https://api.github.com/users/fsonntag/received_events", "type": "User", "site_admin": false}, "created_at": "2017-06-22T06:38:49Z", "updated_at": "2017-06-22T07:21:45Z", "author_association": "CONTRIBUTOR", "body": "I'm also running in this issue on 1.8.2, nevertheless only after processing multiple documents in parallel:\r\n```\r\nFile \"spacy/syntax/parser.pyx\", line 214, in spacy.syntax.parser.Parser.__call__ (spacy/syntax/parser.cpp:7989)\r\nspacy.syntax.parser.ParserStateError: Error analysing doc -- no valid actions available. This should never happen, so please report the error on the issue tracker. Here's the thread to do so --- reopen it if it's closed:\r\nhttps://github.com/spacy-io/spaCy/issues/429\r\nPlease include the text that the parser failed on, which is:\r\n'NSPc1, a mainly nuclear localized protein of novel PcG family members, has a transcription repression activity related to its PKC phosphorylation site at S183. Nervous system polycomb 1 (NSPc1) shares high homology with verteb\r\nrate PcG proteins Mel-18 and Bmi-1. The mRNA of NSPc1 is highly expressed in the developmental nervous system [Mech. Dev. 102 (2001) 219-222]. However, the functional characterization of NSPc1 protein is not clear. In the prese\r\nnt study, using Western blotting technique, we aimed to describe the distributions of NSPc1 protein in rat tissues and cell lines. The subcellular localization of NSPc1 was examined in HeLa and SH-SY5Ycell lines, and its transc\r\nriptional repression activity was examined in COS-7 cell line. We found that the NSPc1 protein was localized mainly in the nucleus. NSPc1 remarkably repressed the transcription. Most interestingly, both the C-terminal of NSPc1 \r\nand two phosphorylation sites in the C-terminal, especially the PKC phosphorylation site at S183, were important in mediating transcription repression. Taken together, results from our study suggest that NSPc1, as a typical PcG\r\n family member, has powerful transcriptional repression ability, which may be related to the PKC signaling pathway.'\r\n```\r\n\r\nEdit: I think it's just the parallelization, that's not done by `nlp.pip`, but instead calling the parser from different threads. So nevermind :)"}, {"url": "https://api.github.com/repos/explosion/spaCy/issues/comments/387515313", "html_url": "https://github.com/explosion/spaCy/issues/429#issuecomment-387515313", "issue_url": "https://api.github.com/repos/explosion/spaCy/issues/429", "id": 387515313, "node_id": "MDEyOklzc3VlQ29tbWVudDM4NzUxNTMxMw==", "user": {"login": "lock[bot]", "id": 33595554, "node_id": "MDM6Qm90MzM1OTU1NTQ=", "avatar_url": "https://avatars1.githubusercontent.com/in/6672?v=4", "gravatar_id": "", "url": "https://api.github.com/users/lock%5Bbot%5D", "html_url": "https://github.com/apps/lock", "followers_url": "https://api.github.com/users/lock%5Bbot%5D/followers", "following_url": "https://api.github.com/users/lock%5Bbot%5D/following{/other_user}", "gists_url": "https://api.github.com/users/lock%5Bbot%5D/gists{/gist_id}", "starred_url": "https://api.github.com/users/lock%5Bbot%5D/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/lock%5Bbot%5D/subscriptions", "organizations_url": "https://api.github.com/users/lock%5Bbot%5D/orgs", "repos_url": "https://api.github.com/users/lock%5Bbot%5D/repos", "events_url": "https://api.github.com/users/lock%5Bbot%5D/events{/privacy}", "received_events_url": "https://api.github.com/users/lock%5Bbot%5D/received_events", "type": "Bot", "site_admin": false}, "created_at": "2018-05-08T19:28:13Z", "updated_at": "2018-05-08T19:28:13Z", "author_association": "NONE", "body": "This thread has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.\n"}]